# Generated by Django 4.2.3 on 2023-07-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.CharField(choices=[('NU', 'Nubank'), ('CE', 'Caixa econômica'), ('IU', 'Itaú Unibanco'), ('BD', 'Bradesco'), ('BB', 'Banco do Brasil'), ('ST', 'Santander'), ('SC', 'Sicoob')], max_length=2),
        ),
    ]
